### ISSUE TITLE
BUG in RegisterListener, wrong null check

### ISSUE THREAD

**Issue by mhascak** [Tpessia/RabbitLight#2]
Hello, 
I identified small bug in ConsumerManager.cs.

You perform null check against `config.OnEnd `but is shout be `config.OnAck`

https://github.com/Tpessia/RabbitLight/blob/9b9c413779e48e0f1cb8000a81f94597bc5d8145/source/Consumer/Manager/ConsumerManager.cs#L190
https://github.com/Tpessia/RabbitLight/blob/9b9c413779e48e0f1cb8000a81f94597bc5d8145/source/Consumer/Manager/ConsumerManager.cs#L191

Thanks

**Comment by Tpessia** [comment]
Thanks!! Just fixed it

https://github.com/Tpessia/RabbitLight/blob/54df38ae9b0e6f8cbeb4d46663ec492f082d0004/source/Consumer/Manager/ConsumerManager.cs#L190

https://github.com/Tpessia/RabbitLight/blob/54df38ae9b0e6f8cbeb4d46663ec492f082d0004/source/Consumer/Manager/ConsumerManager.cs#L191
